name: catkin_make_isolated

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        compiler: ["-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++", "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"]
    steps:
    - uses: actions/checkout@v1
      with:
        path: ws/src/cslibs_navigation_utilities
    - uses: betwo/github-setup-catkin@v1.0.0
      with:
        ros-version: 'melodic'
        workspace: $HOME/work/cslibs_navigation_utilities/ws
    - name: build
      run: |
        cd $HOME/work/cslibs_navigation_utilities/ws
        sudo apt-get install -qq -y gcc clang 
        catkin_make_isolated ${{ matrix.compiler }}
    - name: test
      run: |
        cd $HOME/work/cslibs_navigation_utilities/ws
        catkin_make_isolated --catkin-make-args run_tests